## Uptrace configuration file.
## See https://uptrace.dev/get/config.html for details.

##
## ClickHouse database credentials.
##
ch:
  addr: uptrace-clickhouse:9000
  user: default
  password:
  database: uptrace

  # TLS configuration. Uncomment to enable.
  # tls:
  #   insecure_skip_verify: true

  # Maximum query execution time.
  max_execution_time: 30s

##
## PostgreSQL db that is used to store metadata such us metric names, dashboards, alerts,
## and so on.
##
pg:
  addr: postgresql:5432
  user: uptrace
  password: uptrace
  database: uptrace

projects:
  - id: 1
    name: Cryptellation
    token: cryptellation_secret_token
    pinned_attrs:
      - service
      - host_name
      - deployment_environment
    group_by_env: false
    group_funcs_by_service: false
    prom_compat: false

auth:
  users:
    - name: John Doe
      email: uptrace@localhost
      password: uptrace
      notify_by_email: true

listen:
  # OTLP/gRPC API.
  grpc:
    addr: ':4317'
    # tls:
    #   cert_file: config/tls/uptrace.crt
    #   key_file: config/tls/uptrace.key

  # OTLP/HTTP API and Uptrace API with Vue UI.
  http:
    addr: ':4318'
    # tls:
    #   cert_file: config/tls/uptrace.crt
    #   key_file: config/tls/uptrace.key